# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('message', models.CharField(max_length=200, verbose_name='\u7559\u8a00')),
            ],
            options={
                'verbose_name': '\u7559\u8a00\u8868',
                'verbose_name_plural': '\u7559\u8a00\u8868',
            },
        ),
    ]
